#!/bin/sh

set -euo pipefail

show_help() {
    cat <<-HELP
til project - til project description handler

USAGE: til project [options] <project>

Opens a new/existing file for the specified project.

Options:
  -l|--list - list existing project files
HELP
}

PROJECT_ROOT=$DOCS_ROOT/projects

while (( $# )); do
    case $1 in
        "-h"|"--help")
            show_help
            exit 1
            ;;
        "-l"|"--list")
            ls_clean $PROJECT_ROOT
            ;;
        *)
            PROJECT_FILE=$PROJECT_ROOT/$1.$DOC_SUFFIX
            ;;
    esac
    shift
done

if [[ -z "${PROJECT_FILE:-''}" ]]; then
    show_help
    exit 1
fi

init_file $PROJECT_FILE

_edit $PROJECT_FILE && git add $PROJECT_FILE
is_empty $PROJECT_FILE && rm $PROJECT_FILE
