#!/bin/sh

set -euo pipefail

show_help() {
    cat <<-HELP
til sync - til remote synchronize

USAGE: til sync

If there is a remote endpoint, will attempt to synchronize the contents between the
local and remote endpoint.
HELP
}

if [[ -n "$(git remote -v)" ]]; then
   setup_remote
   git pull --rebase
   git push
fi
