#!/bin/sh

set -euo pipefail

show_help() {
    cat <<-HELP
til topic - til topic handler

USAGE: til topic [options] <topic>

Opens a new/existing file for the specified topic/subtopic.  <topic> can be
hierarchical such as 'topic/subtopic'.

Options:
  -l|--list - list existing topics
HELP
}

if [[ $# < 1 ]]; then
    show_help
    exit 1
fi

TOPIC_ROOT=$DOCS_ROOT/topics

if [[ ! -d $TOPIC_ROOT ]]; then
    log "Creating $TOPIC_ROOT\..."
    mkdir -p $TOPIC_ROOT
fi

while (( $# )); do
    case "$1" in
        "-h"|"--help")
            show_help
            exit 1
            ;;
        "-l"|"--list")
            ls_clean $TOPIC_ROOT
            ;;
        *)
            TOPIC_FILE=$TOPIC_ROOT/$1.$DOC_SUFFIX
            init_file $TOPIC_FILE
            _edit $TOPIC_FILE && _add $TOPIC_FILE
        ;;
    esac
    shift
done
