#!/usr/bin/env bash

set -euo pipefail

# Normalize runtime
TIL_ROOTDIR="$(dirname $(realpath $0))/.."
source $(readlink --canonicalize "$TIL_ROOTDIR/src/lib")

show_help() {
    cat <<HELP
til - command line management of knowledge repository

USAGE: til <action> [options]

type the command with -h|--help to view information about it.

Actions are:
  browse  - opens browser of repository directory
  commit  - commits current changes to the git repository
  diary   - opens the current day's logbook entry for editting
  grep    - searches for a phrase in the repository
  project - opens a new/existing entry for a specified project
  tag     - shows entries containing the specified tag
  todo    - manage todo list
  topic   - opens a new/existing entry for a topic or subtopic
  sync    - if a remote repository is defined, will attempt to sync with it
HELP
}

if [[ $# < 1 ]]; then
    show_help
    exit 1
fi

while (( $# )); do
    case "$1" in
        "-h"|"--help")
            show_help
            exit 1
            ;;
        "commit"|"save")
            cd $TILHOME
            git commit -av
            exit $?
            ;;
        *)
            ACTION="$1"
            shift
            source $(readlink --canonicalize "$TIL_ROOTDIR/src/commands/$ACTION")
            break
            ;;
    esac
    shift
done
